# Etapa de construcción
FROM node:20.5.0-alpine3.18 as build-stage

WORKDIR /app/
COPY package*.json ./
RUN npm install
COPY . .
RUN ["npm", "run", "build"]

# Etapa de producción
FROM nginx:1.25.1-alpine3.17-slim
# Copiar los archivos de configuración de NGINX
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
# Copiar los archivos construidos
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]

