version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod    
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped