services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod    
    ports:
      - "80:80"
      - "443:443"  # Añadimos el puerto 443 para HTTPS
    volumes:
      - ./ssl:/etc/nginx/ssl:ro  # Montamos los certificados SSL
      # - ./src:/app/src  # Comentamos esta línea
    environment:
      - NODE_ENV=production
    restart: unless-stopped